export const queryKeys = {
  me: ["me"] as const,
  organization: ["organization", "current"] as const,
  projects: ["projects"] as const,
  project: (projectId: string) => ["projects", projectId] as const,
  workbench: ["workbench"] as const,
  notificationsBadge: ["notifications", "badge"] as const,
  orgQuota: ["org-quotas", "current"] as const,
  testCases: (params: Record<string, string>) => ["test-cases", params] as const,
  testCase: (id: string) => ["test-cases", id] as const,
  testPlans: (params: Record<string, string>) => ["test-plans", params] as const,
  testRuns: (params: Record<string, string>) => ["test-runs", params] as const,
  testRun: (id: string) => ["test-runs", id] as const,
  caseResults: (runId: string) => ["test-runs", runId, "case-results"] as const,
  clusters: (runId: string) => ["test-runs", runId, "failure-clusters"] as const,
  trajectory: (runId: string) => ["test-runs", runId, "trajectory"] as const,
  approvals: (params: Record<string, string>) => ["approval-requests", params] as const,
  approval: (id: string) => ["approval-requests", id] as const,
  gatePolicies: (params: Record<string, string>) => ["quality-gate-policies", params] as const,
  gateEvaluations: (params: Record<string, string>) => ["gate-evaluations", params] as const,
  environments: (params: Record<string, string>) => ["execution-environments", params] as const,
  executionOptions: (projectId: string) => ["execution-options", projectId] as const,
  evidence: (params: Record<string, string>) => ["evidence-objects", params] as const,
  audit: (params: Record<string, string>) => ["audit-events", params] as const,
  cost: ["ai", "cost-dashboard"] as const,
  modelRoutes: ["model-routes"] as const,
  connectors: (params: Record<string, string>) => ["connectors", params] as const,
  apiTokens: ["api-tokens"] as const,
  releaseTasks: (params: Record<string, string>) => ["release-tasks", params] as const,
  members: (projectId: string) => ["projects", projectId, "members"] as const,
};
